// LOG IN 
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCSESS = 'USER_LOGIN_SUCSESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL' 
export const USER_LOGOUT = 'USER_LOGOUT' 

// NEW REGISTER : 
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCSESS = 'USER_REGISTER_SUCSESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL' 


// USER DETAILS :
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCSESS = 'USER_DETAILS_SUCSESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL' 


// USER UPDATE PROFILE :
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCSESS = 'USER_UPDATE_PROFILE_SUCSESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL' 
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET' 